import { MigrationInterface, QueryRunner } from "typeorm";

export class Init2Project1779123206950 implements MigrationInterface {
    name = 'Init2Project1779123206950'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "sections_coach_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP CONSTRAINT "competitions_organizer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP CONSTRAINT "competition_registrations_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP CONSTRAINT "competition_registrations_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP CONSTRAINT "competition_registrations_judge_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "competition_results_competition_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "competition_results_registration_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "competition_results_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "competition_results_judge_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_section_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_section_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sections_coach"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comp_regs_competition"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comp_regs_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_results_competition"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enrollments_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_enrollments_section"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendance_user_section"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_section_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "attendance_user_id_section_id_date_key"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'coach', 'athlete', 'judge')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'athlete'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sections" ALTER COLUMN "coach_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."competition_status_enum" RENAME TO "competition_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."competitions_status_enum" AS ENUM('upcoming', 'ongoing', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" TYPE "public"."competitions_status_enum" USING "status"::"text"::"public"."competitions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" SET DEFAULT 'upcoming'`);
        await queryRunner.query(`DROP TYPE "public"."competition_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."registration_status_enum" RENAME TO "registration_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."competition_registrations_status_enum" AS ENUM('pending', 'approved', 'rejected', 'withdrawn')`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" TYPE "public"."competition_registrations_status_enum" USING "status"::"text"::"public"."competition_registrations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."registration_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP COLUMN "judge_id"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD "judge_id" character varying`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "competition_results_registration_id_key"`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum" RENAME TO "enrollment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('active', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" TYPE "public"."enrollments_status_enum" USING "status"::"text"::"public"."enrollments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_ab38c6afcbb75a836fcfd196b6e" FOREIGN KEY ("coach_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD CONSTRAINT "FK_44e04509827273880822fb4eb78" FOREIGN KEY ("organizer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD CONSTRAINT "FK_be6b6ee51209a66b81c39b267a0" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD CONSTRAINT "FK_27f39b0f1c0c614a7b47b7e6611" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "FK_ad99acdb668877a36b7e8436405" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "FK_d42fc14c21718ecd46f13e41840" FOREIGN KEY ("registration_id") REFERENCES "competition_registrations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "FK_cc457c60ac5775202aae6c5996a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "FK_f02a4f40edb2ed3123f3fc493a8" FOREIGN KEY ("judge_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_ebbb1eaa243b6fd10a61fe38c78" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_ff997f5a39cd24a491b9aca45c9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_005fdbba9ac200693005f5ab21f" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_24ca79eed4c4ef0bc8cfb634b5b" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_0bedbcc8d5f9b9ec4979f519597" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_0bedbcc8d5f9b9ec4979f519597"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_24ca79eed4c4ef0bc8cfb634b5b"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_005fdbba9ac200693005f5ab21f"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_ff997f5a39cd24a491b9aca45c9"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_ebbb1eaa243b6fd10a61fe38c78"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "FK_f02a4f40edb2ed3123f3fc493a8"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "FK_cc457c60ac5775202aae6c5996a"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "FK_d42fc14c21718ecd46f13e41840"`);
        await queryRunner.query(`ALTER TABLE "competition_results" DROP CONSTRAINT "FK_ad99acdb668877a36b7e8436405"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP CONSTRAINT "FK_27f39b0f1c0c614a7b47b7e6611"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP CONSTRAINT "FK_be6b6ee51209a66b81c39b267a0"`);
        await queryRunner.query(`ALTER TABLE "competitions" DROP CONSTRAINT "FK_44e04509827273880822fb4eb78"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_ab38c6afcbb75a836fcfd196b6e"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_status_enum_old" AS ENUM('active', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" TYPE "public"."enrollment_status_enum_old" USING "status"::"text"::"public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum_old" RENAME TO "enrollment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "competition_results_registration_id_key" UNIQUE ("registration_id")`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" DROP COLUMN "judge_id"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD "judge_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."registration_status_enum_old" AS ENUM('pending', 'approved', 'rejected', 'withdrawn')`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" TYPE "public"."registration_status_enum_old" USING "status"::"text"::"public"."registration_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."competition_registrations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."registration_status_enum_old" RENAME TO "registration_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."competition_status_enum_old" AS ENUM('upcoming', 'ongoing', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" TYPE "public"."competition_status_enum_old" USING "status"::"text"::"public"."competition_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "competitions" ALTER COLUMN "status" SET DEFAULT 'upcoming'`);
        await queryRunner.query(`DROP TYPE "public"."competitions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."competition_status_enum_old" RENAME TO "competition_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sections" ALTER COLUMN "coach_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('admin', 'coach', 'athlete', 'judge')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'athlete'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_user_id_section_id_date_key" UNIQUE ("section_id", "user_id", "date")`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_section_id_user_id_key" UNIQUE ("section_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "idx_attendance_user_section" ON "attendance" ("section_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollments_section" ON "enrollments" ("section_id") `);
        await queryRunner.query(`CREATE INDEX "idx_enrollments_user" ON "enrollments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_results_competition" ON "competition_results" ("competition_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comp_regs_user" ON "competition_registrations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comp_regs_competition" ON "competition_registrations" ("competition_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sections_coach" ON "sections" ("coach_id") `);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "attendance_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "competition_results_judge_id_fkey" FOREIGN KEY ("judge_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "competition_results_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "competition_results_registration_id_fkey" FOREIGN KEY ("registration_id") REFERENCES "competition_registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_results" ADD CONSTRAINT "competition_results_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD CONSTRAINT "competition_registrations_judge_id_fkey" FOREIGN KEY ("judge_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD CONSTRAINT "competition_registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competition_registrations" ADD CONSTRAINT "competition_registrations_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitions" ADD CONSTRAINT "competitions_organizer_id_fkey" FOREIGN KEY ("organizer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "sections_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
